server:
  port: 8087
spring:
  application:
    name: backoffice-bff
  threads:
    virtual:
      enabled: true
  profiles:
    active: dev
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://identity/realms/Yas
        registration:
          api-client:
            provider: keycloak
            client-id: backoffice-bff
            client-secret: TVacLC0cQ8tiiEKiTVerTb2YvwQ1TRJF
            scope: openid, profile, email, roles
management:
  tracing:
    sampling:
      probability: "1.0"
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
    tags:
      application: ${spring.application.name}
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
---
spring:
  config:
    activate:
      on-profile: "dev"
  cloud:
    gateway:
      routes:
        - id: api_product_local
          uri: http://localhost:8080
          #uri: http://api.yas.local
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - TokenRelay=
        - id: api_location_local
          uri: http://localhost:8086
          #          uri: http://api.yas.local
          predicates:
            - Path=/api/location/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - TokenRelay=
        - id: api_inventory_local
          uri: http://localhost:8090
          #          uri: http://api.yas.local
          predicates:
            - Path=/api/inventory/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - TokenRelay=
        - id: api_cart_local
          uri: http://localhost:8084
          #          uri: http://api.yas.local
          predicates:
            - Path=/api/cart/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - TokenRelay=
        - id: api_customer_local
          uri: http://localhost:8088
          #          uri: http://api.yas.local
          predicates:
            - Path=/api/customer/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - TokenRelay=
        - id: api_media_local
          uri: http://localhost:8083
          #          uri: http://api.yas.local
          predicates:
            - Path=/api/media/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - TokenRelay=
        - id: api_rating_local
          uri: http://localhost:8089
          #          uri: http://api.yas.local
          predicates:
            - Path=/api/rating/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - TokenRelay=
        - id: api_tax_local
          uri: http://localhost:8091
          #          uri: http://api.yas.local
          predicates:
            - Path=/api/tax/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - TokenRelay=
        - id: api_promotion_local
          uri: http://localhost:8092
          #          uri: http://api.yas.local
          predicates:
            - Path=/api/promotion/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - TokenRelay=
        - id: api_search_local
          uri: http://localhost:8092
          #          uri: http://api.yas.local
          predicates:
            - Path=/api/search/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - TokenRelay=
        - id: api_order_local
          uri: http://localhost:8085
#            uri: http://api.yas.local
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - TokenRelay=
        - id: api
          #uri: http://localhost:8080
          uri: http://api.yas.local
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - TokenRelay=
        - id: nextjs
          uri: http://localhost:3000
          predicates:
            - Path=/**
---
spring:
  config:
    activate:
      on-profile: "prod"
  cloud:
    gateway:
      routes:
        - id: api
          uri: http://product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - TokenRelay=
        - id: nextjs
          uri: http://localhost:3000
          predicates:
            - Path=/**
